name: Build and deploy Node.js app to Azure Web App - AdopleAI-Marketplace (OIDC)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies and build
        env:
          NPM_CONFIG_LEGACY_PEER_DEPS: true
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          auth-type: 'oidc'
          tenant-id: '333d7ebd-77f9-4318-a859-f63db2bd8201'   # Hardcoded Tenant ID

      - name: Verify Azure Login
        run: az account show

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AdopleAI-Marketplace'
          package: .
